import type { Metadata } from "next";
import { Geist, Geist_Mono , Comforter} from "next/font/google";
import "./globals.css";  /* 导入全局css */




const comforter = Comforter({
  variable: "--font-comforter-sans",
  subsets: ["latin"],
  weight: '400',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${comforter.variable} ${geistSans.variable} ${geistMono.variable} antialiased`} >        
        {children}
      </body>
    </html>
  );
}
